# Generated by Django 5.2.8 on 2025-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='error_message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
